# Generated by Django 5.0.3 on 2024-04-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_question_tag_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
