# Generated by Django 5.0.3 on 2024-04-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_like_number_question_like_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
